{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "task-manager.fullname" . }}
  labels:
    {{- include "task-manager.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "task-manager.api.fullname" $ }}
                port:
                  name: http
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: {{ include "task-manager.api.fullname" $ }}
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "task-manager.web.fullname" $ }}
                port:
                  name: http
    {{- end }}
{{- end }}
