apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo-appsofapps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/najiboulhouch/demo-k8s
    targetRevision: main
    path: Devops/argocd/appsofapps/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-appsofapps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
