apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: nginx-demo
            namespace: nginx-appset
          - app: redis
            namespace: redis-appset
          - app: monitoring
            namespace: monitoring-appset
  template:
      metadata:
        name: '{{app}}-appset'
        namespace: '{{namespace}}'
      spec:
        project: default
        source:
          repoURL: https://github.com/najiboulhouch/demo-k8s
          targetRevision: main
          path: 'Devops/argocd/applicationset/{{app}}'
        destination:
          server: https://kubernetes.default.svc
          namespace: '{{namespace}}'
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true