apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-manager
  labels:
    app.kubernetes.io/name: task-manager
spec:
  ingressClassName: nginx
  rules:
    - host: task-manager.local
      http:
        paths:
          # Préfixe le plus long en premier (nginx ingress)
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: task-manager-api
                port:
                  name: http
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: task-manager-api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: task-manager-web
                port:
                  name: http
